#include <xc.h> //ARQUIVO READER CONTENDO AS CONFIGURAÇÕES DO uC

#pragma config FOSC = INTIO67 //CONFIG. PARA UTILIZAR OSCILADOR INTERNO
#pragma config PBADEN = OFF //DESATIVANDO CONVERSOR ANALOGICO/DIGITAL

#define _XTAL_FREQ 1000000 //SETTANDO A FREQUENCIA 1MHz

void __interrupt() paradaSolicitada(){ //FUNÇÃO DE INTERRUPÇÃO
    if (INTCONbits.INT0IF == 1){ //SE FLAG DE INTERRUPÇÃO ALTA, LOGO OCORREU
        INTCONbits.INT0IF = 0; //LIMPANDO FLAG DA INTERRUPÇÃO
        
        PORTD = 0b00000001;
        __delay_ms(1000);
    }
}

void main(void) {
    
    OSCCONbits.IRCF = 0b011;
    
    TRISD = 0b11111110; //CONFIGURANDO AS PORTAS D PARA ENTRADA E SAIDA
    TRISBbits.RB0 = 1; //CONFIG. BOTAO RB0(SW0) COMO ENTRADA
    
    INTCONbits.INT0IE = 1; //HABILITANDO INTERRUPÇÃO EXTERNA INT0 (PINO RB0)
    INTCONbits.INT0IF = 0; //LIMPANDO A FLAG DE INTERRUPÇÕES INT0
    INTCON2bits.INTEDG0 = 0; //HABILITANDO INTERRUPÇÃO INT0 NA BORDA DESCIDA
    
    RCONbits.IPEN = 0; //DESLIGANDO PRIORIDADES NA INTERRUPÇÃO
    INTCONbits.GIE = 1; //HABILITANDO INTERRUPÇÃO GERAL
    
    while(1){
        PORTDbits.RD0 = 0;
    }
    
    return;
}
